version: '3.6'

services:
    todo-php-fpm:
        build:
            context: ./
            dockerfile: .docker/php-fpm/Dockerfile
        image: todo/php-fpm
        volumes:
            - ./:/code/

    todo-nginx:
        build:
            context: ./
            dockerfile: ./.docker/nginx/Dockerfile
        image: todo/nginx
        ports:
            - 8000:80
        volumes:
            - ./public:/code/public

    todo-postgres:
        image: postgres:10-alpine
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=root

    todo-php-cli:
        build:
            context: ./
            dockerfile: ./.docker/php-cli/Dockerfile
        image: todo/php-cli

    todo-project-todo:
        image: todo/php-cli
        command: php bin/todo project:todos
        volumes:
            - ./:/code/

    todo-mailcatcher:
        image: tophfr/mailcatcher
        ports:
            - 1080:80
