version: '3.6'

services:
    todo-php-fpm:
        build:
            context: ./
            dockerfile: .docker/php-fpm/Dockerfile
        image: todo/php-fpm
        volumes:
            - ./:/code/

    todo-nginx:
        build:
            context: ./
            dockerfile: ./.docker/nginx/Dockerfile
        image: todo/nginx
        ports:
            - 8000:80
        volumes:
            - ./public:/code/public

    todo-mysql:
        image: mysql:5.7
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=todo
            - MYSQL_ROOT_PASSWORD=root

    todo-php-cli:
        build:
            context: ./
            dockerfile: ./.docker/php-cli/Dockerfile
        image: todo/php-cli

    todo-project-todo:
        image: todo/php-cli
        command: php bin/todo project:todos

    todo-mailcatcher:
        image: tophfr/mailcatcher
        ports:
            - 1080:80
